version: "3"
services:
  redis-server:
    image: "redis"
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "redis-server"

  nginx:
    image: nginx
    depends_on:
      - "app"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
